version: "3.9"

services:
  php8.2:
    container_name: php_service
    build:
      context: ./docker/php8.2
    hostname: php8.2
    ports:
      - "10001:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8.2/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  nginx:
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    depends_on:
      - php8.2
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    networks:
      - backend

  elastic:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - elastic_container=true
    networks:
      - backend

networks:
  backend:
    driver: bridge
